name: Flutter Web
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build Web
    env:
      my_secret: ${{secrets.commit_secret}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter config --enable-web
      - name: Setting .env
        run: |
          echo "APP_NAME=${{ secrets.APP_NAME }}" >> .env
          echo "GOOGLE_MAP_KEY=${{ secrets.GOOGLE_MAP_KEY }}" >> .env
          cat .env
      - run: flutter pub get
      - run: flutter build web --release
      - name: Sync Bucket
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          AWS_EC2_METADATA_DISABLED: true
        run: |
          aws s3 sync \
            --region ap-northeast-2 \
            build ${{secrets.AWS_BUCKET_NAME}} \
            --delete

      - name: Invalidate cache CloudFront
        uses: chetan/invalidate-cloudfront-action@master
        env:
          DISTRIBUTION: ${{secrets.DISTRIBUTION_ID}}
          PATHS: '/index.html'
        continue-on-error: true