name: Flutter Web
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build Web
    env:
      my_secret: ${{secrets.commit_secret}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter config --enable-web
      - name: Setting .env
        run: |
          echo "APP_NAME=${{ secrets.APP_NAME }}" >> .env
          echo "GOOGLE_MAP_KEY=${{ secrets.GOOGLE_MAP_KEY }}" >> .env
          cat .env
      - run: flutter pub get
      - run: flutter build web --release
      - name: Upload build file
        uses: actions/upload-artifact@v3
        with:
          name: web-artifact
          path: build/web
  deploy:
    name: Deploy Web to Aws S3
    runs-on: ubuntu-latest
    needs: build
    env:
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      AWS_EC2_METADATA_DISABLED: true
    steps:
      - name: Download build file
        uses: actions/download-artifact@v3
        with:
          name: web-artifact
          path: build/web
      - name: Sync Bucket
        run: aws s3 sync build/web --region ap-northeast-2 ${{secrets.AWS_BUCKET_NAME}} --delete
      - name: Invalidate cache CloudFront
        run: aws cloudfront create-invalidation --distribution-id ${{secrets.AWS_DISTRIBUTION_ID}} --paths "/*"
        continue-on-error: true